# Minimal working example for ClusterAlgebras.jl
# Run with:  julia --project=. examples/demo.jl
#
# A cluster algebra is generated by repeatedly applying mutation to a
# starting "seed" (a quiver + a set of rational functions called cluster
# variables).  The key theorem (Laurent phenomenon): every cluster variable
# produced by any sequence of mutations is actually a LAURENT POLYNOMIAL in
# the initial variables -- not merely a rational function.

using ClusterAlgebras

# ─────────────────────────────────────────────────────────────────────────────
# 1. QUIVER
#    A Quiver is a directed weighted graph encoded as a skew-symmetrizable
#    integer matrix B.  B[i,j] > 0 means there are B[i,j] arrows from i to j.
# ─────────────────────────────────────────────────────────────────────────────

# The simplest non-trivial example: the A₂ quiver  1 → 2
B = [0 1; -1 0]
q = Quiver(B)

println("A₂ quiver")
println("  exchange matrix B = ", q.B)
println("  mutable vertices  = ", q.n_mutable, "  frozen = ", q.n_frozen)
println("  vertex labels     = ", q.labels)

# Frozen vertices are fixed points of mutation (boundary conditions).
# Here vertex 3 is frozen (a coefficient): mutable: 1,2  frozen: 3.
B_fr = [0 1 1; -1 0 1; -1 -1 0]
q_fr = Quiver(B_fr, 2)
println("\nQuiver with frozen vertex 3")
println("  n_mutable = ", q_fr.n_mutable, "  n_frozen = ", q_fr.n_frozen)

# Skew-symmetrizable (non simply-laced types, e.g. B₂): needs symmetrizers d.
# d[i]*B[i,j] == -d[j]*B[j,i].  Here d = [2,1]: 2·1 = -1·(-2). ✓
B_B2 = [0 1; -2 0]
q_B2 = Quiver(B_B2, 2, [2, 1], ["a", "b"])
println("\nB₂ quiver (skew-symmetrizable)  B = ", q_B2.B, "  d = ", q_B2.d)

# ─────────────────────────────────────────────────────────────────────────────
# 2. VISUALISATION (DOT format -- paste at graphviz.org or pipe to `dot`)
# ─────────────────────────────────────────────────────────────────────────────

println("\nDOT representation of the A₂ quiver:")
println(to_dot(q))

println("DOT representation of the B₂ quiver (labeled arrow for weight 2):")
println(to_dot(q_B2))

println("DOT representation with frozen vertex (box shape):")
println(to_dot(q_fr))

# ─────────────────────────────────────────────────────────────────────────────
# 3. QUIVER MUTATION
#    Mutation at vertex k transforms B by Fomin–Zelevinsky's rule:
#      B'[i,j] = -B[i,j]                          if i=k or j=k
#      B'[i,j] =  B[i,j] + (|B[i,k]|B[k,j] + B[i,k]|B[k,j]|)/2  otherwise
# ─────────────────────────────────────────────────────────────────────────────

println("\n", "─"^60)
println("QUIVER MUTATION")
println("─"^60)

# A₃: 1→2→3
B_A3 = [0 1 0; -1 0 1; 0 -1 0]
q_A3 = Quiver(B_A3)

q_mut = mutate(q_A3, 2)   # mutate at vertex 2
println("\nA₃ mutated at vertex 2:")
println("  before: ", q_A3.B)
println("  after : ", q_mut.B)

# Mutation is an involution: μ_k ∘ μ_k = id
println("  μ₂∘μ₂ = id? ", mutate(q_mut, 2).B == q_A3.B)

# Mutation sequences: pass a vector of vertex indices
q_seq = mutate(q_A3, [1, 2, 1])
println("\nA₃ after mutation sequence [1,2,1]:  B = ", q_seq.B)

# ─────────────────────────────────────────────────────────────────────────────
# 4. SEED
#    A Seed wraps a Quiver with cluster variables -- elements of the fraction
#    field of Z[x₁,...,xₙ].  The initial cluster is just {x₁, x₂, ...}.
# ─────────────────────────────────────────────────────────────────────────────

println("\n", "─"^60)
println("SEEDS")
println("─"^60)

s = Seed(q)              # A₂ seed, variables x1, x2 (auto-named)
println("\nInitial A₂ seed:  cluster = ", s.cluster)

s_named = Seed(q, ["x", "y"])   # custom names
println("Initial A₂ seed:  cluster = ", s_named.cluster)

# ─────────────────────────────────────────────────────────────────────────────
# 5. SEED MUTATION  (the exchange relation)
#    x_k' = (∏_{B[i,k]>0} x_i^{B[i,k]}  +  ∏_{B[i,k]<0} x_i^{-B[i,k]}) / x_k
#    The quiver mutates simultaneously.
# ─────────────────────────────────────────────────────────────────────────────

println("\n", "─"^60)
println("SEED MUTATION")
println("─"^60)

s0 = Seed(q, ["x", "y"])

s1 = mutate(s0, 1)       # x → (1+y)/x
println("\nAfter μ₁:  x → ", s1.cluster[1], "  y → ", s1.cluster[2])

s2 = mutate(s0, 2)       # y → (1+x)/y
println("After μ₂:  x → ", s2.cluster[1], "  y → ", s2.cluster[2])

# Involutivity of seed mutation
println("μ₁∘μ₁ restores x? ", mutate(s1, 1).cluster[1] == s0.cluster[1])

# ─────────────────────────────────────────────────────────────────────────────
# 6. THE LAURENT PHENOMENON
#    The A₂ cluster algebra is of finite type: exactly 5 cluster variables.
#    Alternating mutations μ₁μ₂μ₁μ₂μ₁ cycle through all 5 and return to start.
#    Every variable is a Laurent polynomial in the initial {x, y}.
# ─────────────────────────────────────────────────────────────────────────────

println("\n", "─"^60)
println("THE LAURENT PHENOMENON  (A₂, 5 cluster variables)")
println("─"^60)

orbit = [s0]
for k in [1, 2, 1, 2, 1]
    push!(orbit, mutate(orbit[end], k))
end

println("\nAll cluster variables seen during μ₁μ₂μ₁μ₂μ₁ orbit:")
seen = Set()
for s in orbit, v in s.cluster
    str = string(v)
    str in seen && continue
    push!(seen, str)
    println("  ", v)
end

println("\nCluster at step 0: ", orbit[1].cluster)
println("Cluster at step 5: ", orbit[end].cluster)
println("Returned to initial cluster? ",
    Set(string.(orbit[end].cluster)) == Set(string.(orbit[1].cluster)))
